# Set the port number of the server don't change it
server:
    port: 8888

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_uchat?characterEncoding=utf-8&serverTimezone=UTC
        # Set the username and password of the database you need to change based on your own database
        username: root
        password: 123456

    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            ddl-auto: update
        show-sql: true


    thymeleaf:
        cache: false
        mode: LEGACYHTML5